### ISSUE TITLE
Base utilizada no sistema

### ISSUE THREAD

**Issue by rmsaitam** [RonildoSouza/G.E.M.A.S#1]
Poderia disponibilizar o banco com as tabelas utilizada no sistema para poder testar?

É comum a maioria publicar projeto no Github e não colocar o BD utilizado no sistema, claro que pode estar vazia, mas o que importa para testar o sistema são as tabelas do banco.

**Comment by RonildoSouza** [comment]
http://byrns.esy.es/gemas/

**Comment by rmsaitam** [comment]
Legal, mas tem o BD para importar no ambiente local?

**Comment by RonildoSouza** [comment]
Depende... qual a real finalidade?

**Comment by rmsaitam** [comment]
Importar o BD no ambiente local e estudar o sistema.
Também poder contribuir com melhorias de modo posso fazer o pull request que você analisa, faz o merge e incluir no projeto.

**Comment by RonildoSouza** [comment]
https://mega.nz/#!8dRC1KZS!m6g3TAUoBoSZIEXW29gyHz9oTnBsgw-lPqJD7IPJsWA

Fique a vontade...rsr
OBS.: Este projeto eu fiz apenas como trabalho de faculdade, atualmente não tenho pretensão de continua-lo... Mas acho interessante o apontamento de ajustes.
